---
# gateway node variables

########################
# Bind9 role variables
########################

bind9_authoritative: true
bind9_forward: false
bind9_recursor: false
bind9_forward_servers: []
bind9_generate_ddns_key: true
bind9_zones:
  - name: "{{ dns_domain }}"
    type: primary
    ddns_update_key: ddnskey
    ddns_update_policy_grant: "zonesub any"
    secondary_servers:
      - 'key "ddnskey"'
    default_ttl: 600
    serial: 2024102002
    refresh: 1D
    retry: 2H
    expire: 1000H
    primary: "ns.{{ dns_domain }}"
    admin: "admin.{{ dns_domain }}"
    ns_records:
      - "ns.{{ dns_domain }}"
    # RR values are either relative to the zone, either with a final dot when outside.
    rrs:
      - label: gateway
        type: A
        rdata: 10.0.0.1
      - label: ns
        type: A
        rdata: 10.0.0.11
      - label: node-pi-1
        type: A
        rdata: 10.0.0.11
      - label: node-asus-1
        type: A
        rdata: 10.0.0.20
      - label: vault
        type: A
        rdata: 10.0.0.11
  - name: 0.10.in-addr.arpa
    type: primary
    default_ttl: 600
    serial: 2024102001
    refresh: 1D
    retry: 2H
    expire: 1000H
    primary: "ns.{{ dns_domain }}"
    admin: "admin.{{ dns_domain }}"
    ns_records:
      - "ns.{{ dns_domain }}."
    rrs:
      - label: 1.0
        type: PTR
        rdata: "gateway.{{ dns_domain }}."
      - label: 11.0
        type: PTR
        rdata: "node-pi-1.{{ dns_domain }}."
      - label: 20.0
        type: PTR
        rdata: "node-asus-1.{{ dns_domain }}."
