---
all:
  children:
    control:
      hosts:
        pimaster:
          hostname: ansible
          ansible_host: localhost
          ansible_connection: local
        #raspi-4 2gb
        gateway:
          hostname: gateway
          ip: 192.168.1.11
          ansible_host: 192.168.1.11
          mac: E4:5F:01:68:12:9E`
    external:
      hosts:
        s3:
          hostname: s3
          ansible_host: s3.watacoso.com
    picluster:
      hosts:
        #raspi-4 4gb
        node1:
          hostname: node1
          ansible_host: 10.0.0.11
          ip: 10.0.0.11
          mac: E4:5F:01:68:12:9E
        #raspi-4 4gb, geekworm fan
        node2:
          hostname: node2
          ansible_host: 10.0.0.12
          ip: 10.0.0.12
          mac: E4:5F:01:63:56:C2
        #raspi-5 8gb
        node3:
          hostname: node3
          ansible_host: 10.0.0.13
          ip: 10.0.0.13
          # TODO: add correct MAC address
          mac: e4:5f:01:2f:49:05
        node-asus-1:
          hostname: node-asus-1
          ansible_host: 10.0.0.20
          ip: 10.0.0.20
          mac: 0C:54:15:D3:69:F4
    geekwormFan:
      hosts:
        node3:
    raspberrypi:
      hosts:
        node[1:3]:
    x86:
      hosts:
        node-asus-1:
    k3s_cluster:
      children:
        k3s_master:
          hosts:
            node1:
        k3s_worker:
          hosts:
            node[2:3]:
            node-asus-1:
    dns:
      hosts:
        node1:
    pxe:
      hosts:
        node1:
    vault:
      hosts:
        node1:
    haproxy:
      hosts:
        node1:
