---
all:
  children:
    control:
      hosts:
        pimaster:
          hostname: ansible
          ansible_host: localhost
          ansible_connection: local
    external:
      hosts:
        s3:
          hostname: s3
          ansible_host: s3.watacoso.com
    picluster:
      hosts:
        node-pi-1:
          hostname: node1
          ansible_host: 10.0.0.11
          ip: 10.0.0.11
          mac: dc:a6:32:9c:29:b9
        node-hp-1:
          hostname: node-asus-1
          ansible_host: 10.0.0.20
          ip: 10.0.0.20
          mac: 18:60:24:21:1c:d4
    raspberrypi:
      hosts:
        node-pi-1:
    x86:
      hosts:
        node-asus-1:
    k3s_cluster:
      children:
        k3s_master:
          hosts:
            node-pi-1:
        k3s_worker:
          hosts:
            node-pi-1:
            node-asus-1:
    dns:
      hosts:
        node-pi-1:
    pxe:
      hosts:
        node-pi-1:
    vault:
      hosts:
        node-pi-1:
    haproxy:
      hosts:
        node-pi-1:
